#!/usr/bin/env python3
"""Draw the generalized-plant block diagram of tutorial chapter 12: docs/figures/tutorial/generalized_plant.svg.

    uv run --with fonttools --with uharfbuzz docs/figures/make_generalized_plant.py [--out FILE]

The two-port picture behind every fixed-structure synthesis of the repository, drawn the way a
paper draws it in TikZ: two plain blocks, P above K, thin ink lines with small filled heads, the
exogenous inputs w and the performance outputs z as bold vectors, the control input u and the
measurement y in italic, and the channel names of build_P_Goland(V, 1, 1, [1 2]) in small
typewriter beside each signal. Text is set from Latin Modern outlines (roman, bold, italic, mono)
through make_wordmark.py, so the SVG needs no font; the canvas is 15 x 6.5 cm at 1 pt per unit on
a white background, sizes 9 pt (letters) and 8 pt (names), the fw_style tokens.
"""
import argparse, os, sys
sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_wordmark import Face, fonts_dir, FACES, INK, MUTED, WHITE

PT = 72 / 2.54
W, H = 15.0 * PT, 6.5 * PT
FS, FS_SMALL = 9, 8
LW_LINE, LW_BLOCK = 0.7, 0.8
HEAD_L, HEAD_W = 5.0, 1.9                       # arrow head length and half width (pt)


class Draw:
    def __init__(self):
        fd = fonts_dir()
        self.face = {k: Face(os.path.join(fd, FACES[k])) for k in ('regular', 'italic', 'bold', 'mono')}
        self.parts = []

    def text(self, s, x, y, face='regular', size=FS, anchor='start', color=INK):
        f = self.face[face]
        w = f.run(s, size)[1]
        x -= {'start': 0.0, 'middle': 0.5, 'end': 1.0}[anchor] * w
        d, _ = f.run(s, size, x, y)
        self.parts.append(f'<path fill="{color}" d="{d}"/>')

    def block(self, x0, y0, x1, y1, label):
        self.parts.append(f'<rect x="{x0}" y="{y0}" width="{x1 - x0}" height="{y1 - y0}" fill="{WHITE}" '
                          f'stroke="{INK}" stroke-width="{LW_BLOCK}"/>')
        self.text(label, 0.5 * (x0 + x1), 0.5 * (y0 + y1) + 0.35 * FS, 'italic', FS, 'middle')

    def arrow(self, pts):
        """Polyline in ink with a filled head at its end; the shaft stops at the head's base."""
        (x0, y0), (x1, y1) = pts[-2], pts[-1]
        n = ((x1 - x0) ** 2 + (y1 - y0) ** 2) ** 0.5
        tx, ty = (x1 - x0) / n, (y1 - y0) / n
        bx, by = x1 - tx * HEAD_L, y1 - ty * HEAD_L
        shaft = ' '.join(f'{x:.2f},{y:.2f}' for x, y in pts[:-1] + [(bx, by)])
        self.parts.append(f'<polyline points="{shaft}" fill="none" stroke="{INK}" stroke-width="{LW_LINE}" '
                          f'stroke-linejoin="miter"/>')
        head = f'{x1:.2f},{y1:.2f} {bx - ty * HEAD_W:.2f},{by + tx * HEAD_W:.2f} {bx + ty * HEAD_W:.2f},{by - tx * HEAD_W:.2f}'
        self.parts.append(f'<polygon points="{head}" fill="{INK}"/>')

    def names(self, lines, x, y, anchor):
        for k, s in enumerate(lines):
            self.text(s, x, y + 10 * k, 'mono', FS_SMALL, anchor, MUTED)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tutorial', 'generalized_plant.svg'))
    a = ap.parse_args()
    d = Draw()
    # blocks: the generalized plant above, the controller below
    P = (165, 28, 265, 98)
    K = (180, 128, 250, 158)
    yw, yu, yk = 48, 78, 143                    # the two rows of P's ports and K's row
    xl, xr = 70, 345                            # the two vertical runs of the loop
    d.block(*P, '$P$'.strip('$'))
    d.block(*K, '$K$'.strip('$'))
    # w -> P -> z: the exogenous inputs and the performance outputs, bold vectors
    d.arrow([(105, yw), (P[0], yw)])
    d.text('w', 150, yw - 5, 'bold', FS, 'middle')
    d.names(['dist_q_f1_ddot', 'dist_q_f2_ddot', 'noise_u_z1_ddot'], 100, yw - 8, 'end')
    d.arrow([(P[2], yw), (325, yw)])
    d.text('z', 280, yw - 5, 'bold', FS, 'middle')
    d.names(['q_f1, q_f2', 'q_f1_dot, q_f2_dot', 'flap1_d'], 330, yw - 8, 'start')
    # y -> K -> u: the measurement leaves P on the right, the demand enters it on the left
    d.arrow([(P[2], yu), (xr, yu), (xr, yk), (K[2], yk)])
    d.text('y', 280, yu - 5, 'italic', FS, 'middle')
    d.names(['u_z1_ddot'], 305, yu + 11, 'middle')
    d.arrow([(K[0], yk), (xl, yk), (xl, yu), (P[0], yu)])
    d.text('u', 150, yu - 5, 'italic', FS, 'middle')
    d.names(['flap1_d'], 118, yu + 11, 'middle')
    hdr = ('<!-- Generalized plant of the FlutterWing tutorial (chapter 12), generated by '
           'docs/figures/make_generalized_plant.py. Text: Latin Modern outlines (GUST Font License). -->')
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W:.2f} {H:.2f}" width="{W:.2f}" height="{H:.2f}">{hdr}'
           f'<rect width="{W:.2f}" height="{H:.2f}" fill="{WHITE}"/>{"".join(d.parts)}</svg>\n')
    with open(a.out, 'w') as f:
        f.write(svg)
    print(f'wrote {a.out} ({W / PT:.0f} x {H / PT:.1f} cm)')


if __name__ == '__main__':
    main()
