function fig = fw_figure(width_cm, height_cm, opts)
%FW_FIGURE  White figure sized in centimetres with the FlutterWing defaults and an exact export size.
%   fig = fw_figure(width_cm, height_cm)
%   fig = fw_figure(width_cm, height_cm, 'Name', 'V-g', 'Visible', 'off')
%   width_cm, height_cm   figure size in cm (default fw_style().size.standard, 14 x 9.8)
%   'Name'          figure name (default '');  'Visible'  'on' (default) | 'off'
%   The figure carries the fw_style tokens as Default* properties: white background (so that an
%   exported figure blends into the page it sits on) and white axes, ink text, axes and grid (major and minor, solid) and colour order [blue; muted] with the
%   four line styles cycled after the colours, 9 pt LaTeX (Computer Modern) for text, tick labels,
%   legends, xline/yline labels, annotation textboxes and colour bars, title in normal weight,
%   legends without box, line width 1.2 and marker size 4. Axes, legends and text set their
%   inherited colours on themselves when they are created, so that the copy the Live Editor
%   displays (a figure without Default* values) keeps them. Write math as $V_\infty$ and escape
%   % _ & in every string. PaperUnits/PaperSize/PaperPosition equal the figure size, so fw_export
%   writes exactly width_cm x height_cm (1102 x 772 px at 200 dpi for the standard size).
%   Example:
%     S = fw_style();  fig = fw_figure(S.size.standard(1), S.size.standard(2), 'Name', 'test');
%     plot(1:10);  xlabel('Velocity (m/s)');  fw_export(fig, 'test.png');
%   See also fw_style, fw_export.

arguments
    width_cm  (1,1) double {mustBePositive} = 14
    height_cm (1,1) double {mustBePositive} = 9.8
    opts.Name (1,:) char = ''
    opts.Visible (1,:) char {mustBeMember(opts.Visible, {'on','off'})} = 'on'
end

S = fw_style();
vis = {};
if strcmp(opts.Visible, 'off'), vis = {'Visible','off'}; end   % an explicit 'on' pops a live script's figure out of the Live Editor
fig = figure('Units','centimeters', 'Color',S.white, 'Name',opts.Name, 'NumberTitle','off', ...
    vis{:}, 'InvertHardcopy','off');
if isprop(fig, 'Theme'), fig.Theme = 'light'; end        % R2025a+: never inherit a dark desktop theme
pos = get(fig, 'Position');                              % keep the screen position, set the size
set(fig, 'Position', [pos(1), pos(2) + pos(4) - height_cm, width_cm, height_cm]);

set(fig, ...
    'DefaultAxesFontSize',S.fontSize, 'DefaultTextFontSize',S.fontSize, ...
    'DefaultLegendFontSize',S.fontSize, ...
    'DefaultAxesTitleFontSizeMultiplier',1, 'DefaultAxesTitleFontWeight','normal', ...
    'DefaultAxesLabelFontSizeMultiplier',1, ...
    'DefaultAxesColor',S.white, 'DefaultAxesBox','on', ...
    'DefaultAxesXColor',S.ink, 'DefaultAxesYColor',S.ink, 'DefaultAxesZColor',S.ink, ...
    'DefaultAxesXGrid','on', 'DefaultAxesYGrid','on', ...
    'DefaultAxesXMinorGrid','on', 'DefaultAxesYMinorGrid','on', ...
    'DefaultAxesGridColor',S.ink, 'DefaultAxesGridAlpha',S.gridAlpha, ...
    'DefaultAxesMinorGridColor',S.ink, 'DefaultAxesMinorGridAlpha',S.minorGridAlpha, ...
    'DefaultAxesMinorGridLineStyle','-', ...
    'DefaultAxesColorOrder',S.cases, 'DefaultAxesLineStyleOrder',S.lineStyles, ...
    'DefaultAxesLineStyleCyclingMethod','aftercolor', ...
    'DefaultLineLineWidth',S.lineWidth, 'DefaultLineMarkerSize',S.markerSize, ...
    'DefaultTextColor',S.ink, ...
    'DefaultLegendColor',S.white, 'DefaultLegendTextColor',S.ink, ...
    'DefaultLegendEdgeColor',S.muted, 'DefaultLegendBox','off', ...
    'DefaultTextInterpreter',S.interpreter, 'DefaultAxesTickLabelInterpreter',S.interpreter, ...
    'DefaultLegendInterpreter',S.interpreter, ...
    'DefaultConstantLineInterpreter',S.interpreter, 'DefaultConstantLineFontSize',S.fontSize, ...
    'DefaultTextboxshapeInterpreter',S.interpreter, 'DefaultTextboxshapeFontSize',S.fontSize, ...
    'DefaultTextboxshapeColor',S.ink, ...
    'DefaultColorbarTickLabelInterpreter',S.interpreter);

% The Live Editor shows a copy of each figure, and the copy has none of these Default* values:
% colours the objects only inherited, the colour order above all, fall back to the MATLAB
% defaults there. So each object sets them on itself when it is created. Font sizes stay
% inherited, because tiledlayout scales them after the axes exist.
set(fig, ...
    'DefaultAxesCreateFcn', @(obj,~) keepValues(obj, {'ColorOrder', 'XColor', 'YColor', 'ZColor', ...
        'GridColor', 'GridAlpha', 'MinorGridColor', 'MinorGridAlpha'}), ...
    'DefaultLegendCreateFcn', @(obj,~) keepValues(obj, {'TextColor', 'EdgeColor'}), ...
    'DefaultTextCreateFcn', @(obj,~) keepValues(obj, {'Color', 'Interpreter'}));

set(fig, 'PaperUnits','centimeters', 'PaperSize',[width_cm height_cm], ...
    'PaperPosition',[0 0 width_cm height_cm], 'PaperPositionMode','manual');
end

function keepValues(obj, props)
%KEEPVALUES  Re-assign each property its current value: its mode turns manual, which a copy keeps.
for k = 1:numel(props)
    obj.(props{k}) = obj.(props{k});
end
end
